spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/${DB_NAME}
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8080